import Foundation
import DataSources
import Quotas
import Mockable

/// Repository protocol for storing provider settings (e.g., isEnabled state).
/// Tests use MockProviderSettingsRepository (generated by @Mockable).
/// App uses JSONSettingsRepository.
@Mockable
public protocol ProviderSettingsRepository: Sendable {
    /// Gets the enabled state for a provider (defaults to true if not set)
    func isEnabled(forProvider id: String) -> Bool

    /// Sets the enabled state for a provider
    func setEnabled(_ enabled: Bool, forProvider id: String)

    /// Gets the enabled state for a provider with a custom default
    func isEnabled(forProvider id: String, defaultValue: Bool) -> Bool

    /// Gets the custom card URL for a provider (nil if not set)
    func customCardURL(forProvider id: String) -> String?

    /// Sets the custom card URL for a provider (empty string or nil to remove)
    func setCustomCardURL(_ url: String?, forProvider id: String)

    /// The `kind` of the data source a provider uses — what Settings calls
    /// PROBE MODE. `nil` until the person picks one.
    func dataSourceKind(forProvider id: String) -> String?

    /// Saves the data source a provider uses.
    func setDataSourceKind(_ kind: String, forProvider id: String)

    /// A provider's on/off setting by name — `claude.cliFallbackEnabled` is
    /// `isOn("cliFallbackEnabled", forProvider: "claude")`. `nil` when never set.
    func stringValue(_ setting: String, forProvider id: String) -> String?
    func setStringValue(_ value: String?, _ setting: String, forProvider id: String)

    func isOn(_ setting: String, forProvider id: String) -> Bool?

    /// Saves a provider's on/off setting by name.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String)

    /// Non-secret values scoped to one login; keys never come from mapping scripts.
    func value(_ setting: String, forProvider id: String) -> JSONValue?
    func setValue(_ value: JSONValue?, _ setting: String, forProvider id: String)

    /// Where the provider's CLI lives on this Mac, when the person chose one
    /// — *CLI location* (#210). `nil` means "find it as usual".
    func cliPath(forProvider id: String) -> String?

    /// Saves the CLI location; `nil` forgets it.
    func setCLIPath(_ path: String?, forProvider id: String)

    /// Gets the quota keys hidden for a provider (issue #140), e.g. a
    /// model-specific window the user never uses. Empty set = show all.
    /// Keys the probe no longer reports are ignored at read time.
    func hiddenQuotaKeys(forProvider id: String) -> Set<String>

    /// Sets the quota keys hidden for a provider (empty set shows all)
    func setHiddenQuotaKeys(_ keys: Set<String>, forProvider id: String)
}

public extension ProviderSettingsRepository {
    func stringValue(_ setting: String, forProvider id: String) -> String? { nil }
    func setStringValue(_ value: String?, _ setting: String, forProvider id: String) {}
    func value(_ setting: String, forProvider id: String) -> JSONValue? { nil }
    func setValue(_ value: JSONValue?, _ setting: String, forProvider id: String) {}
    func scopedValues(forProvider id: String) -> any SettingStore {
        ScopedSettings(repository: self, id: id)
    }

    /// Default for conformers that keep no choice: the definition's default applies.
    func dataSourceKind(forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no choice.
    func setDataSourceKind(_ kind: String, forProvider id: String) {}

    /// Default for conformers that keep no such setting.
    func isOn(_ setting: String, forProvider id: String) -> Bool? { nil }

    /// Default for conformers that keep no such setting.
    func setOn(_ on: Bool, _ setting: String, forProvider id: String) {}

    /// Default for conformers that keep no such setting: find the CLI as usual.
    func cliPath(forProvider id: String) -> String? { nil }

    /// Default for conformers that keep no such setting.
    func setCLIPath(_ path: String?, forProvider id: String) {}

    /// Default for conformers that keep no such setting: every quota is watched.
    func hiddenQuotaKeys(forProvider id: String) -> Set<String> { [] }

    /// Default for conformers that keep no such setting.
    func setHiddenQuotaKeys(_ keys: Set<String>, forProvider id: String) {}
}

// MARK: - Default Implementation

public extension ProviderSettingsRepository {
    /// Default implementation that uses `true` as the default value
    func isEnabled(forProvider id: String) -> Bool {
        isEnabled(forProvider: id, defaultValue: true)
    }
}

private struct ScopedSettings: SettingStore {
    let repository: any ProviderSettingsRepository
    let id: String
    func value(_ name: String) -> JSONValue? { repository.value(name, forProvider: id) }
    func setValue(_ value: JSONValue?, for name: String) { repository.setValue(value, name, forProvider: id) }
}
